### PR TITLE
[ADD] Model for FDB allergy

### PR DESCRIPTION
**Pull request by lasley**
[ADD] Model for FDB allergens
* Add model for FDB allergen group (fdrdamagd)
* Add model for FDB allergen relation (fdrhiclsq)
* Add model for FDB allergen (fdrhicd)
* Add ForeignKeys to patient allergy
* Clean up patient allergy

[IMP] coveragerc: Fix tests exclusion regex

### CODE REVIEW

**Comment by lasley** [comment]
Actually don't merge this yet, I'm going to add `hic`

**Comment by t3ddftw** [comment]
Cool, tag me when it's ready :)

**Comment by lasley** [comment]
Prelim models created, waiting for confirmation of evaluation from CP

**Comment by lasley** [comment]
This is ready for review. Coverage drop is superficial.

**Comment by lasley** [comment]
Crap I did a wrong model. WIP

**Comment by lasley** [comment]
Alright gtg

**Comment by lasley** [comment]
AFAIK the FDB tables are straight copied from FDB. We can blame them for this conundrum

**Pull request merged**
