### PR TITLE
[IMP] Implement Enum for order state definitions

### PR DESCRIPTION
**Pull request by lasley**
* Create EnumOrderState for definitions of state per spec
* Prefer Enum to Integer in order_status

### CODE REVIEW

**Comment by lasley** [comment]
@obulkin Please review when you get a chance. No need for functional, code + passing tests is fine

**Comment by lasley** [comment]
Hah ok maybe not - stupid enum. I'll get back on this 😛

**Comment by lasley** [comment]
Alright yeah I had to go bleeding edge on SQLAlchemy for ENum support. LABS-310 for bumping to final when out. 

This is ready for review

**Comment by t3ddftw** [comment]
👍

**Pull request merged**
